### ISSUE TITLE
TODO: List

### ISSUE THREAD

**Issue by Xelvaris** [Sykes368/SGCraft#1]
- [X] Fix Naquadah ore generation
  - Make Naquadah ore generate only in overworld by default
  - Add config option to allow customization of dimensions naquadah can generate in.
- [ ] Add Transport rings 
- [ ] Texture updates and fixes
- [ ] Make it so all parts of stargates can be camouflaged in both in vertical and horizontal orientations
- [ ] Add Trinium
- [ ] Add Tok'ra tunnels
- [ ] Add Naquadah Reactor/Generator
  - [ ] Create model and texture
  - [ ] Add refined Naquadah
